name: Generate and Push Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up virtual environment and install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Report Generation
        run: |
          . venv/bin/activate
          make run

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Commit and Push Report
        env:
          GITHUB_TOKEN: ${{ secrets.IDS_TOKEN }}
        run: |
          git add WealthData_Summary_Report.md
          git commit -m "Auto-generate performance report [ci skip]" || echo "No changes to commit"
          git push origin HEAD:main
