name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Set up virtual environment and install dependencies
      - name: Set up virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      #     pip install jupyter nbval ipykernel

      # # Install the Python kernel for Jupyter
      # - name: Install Jupyter kernel
      #   run: |
      #     . venv/bin/activate
      #     python -m ipykernel install --user

      # Run the tests within the virtual environment
      - name: Run tests
        run: |
          . venv/bin/activate
          make test
